---
meta:

  concourse:
    url:              (( param "Specify your concourse url" ))
    username:         (( param "Specify your concourse username" ))
    password:         (( param "Specify your concourse password" ))

  project:
    name:             (( param "Specify the name of the project" ))
    pipeline:         (( param "Specify the name of the pipeline" ))
    git_uri:          (( param "Specify git repository URI for your app" ))
    git_key:          (( param "Specify git repository private key" ))
    docker_repo:      (( param "Specify docker repository" ))

resource_types:

- name: pipeline-git-branch-resource-type
  type: docker-image
  source:
    repository: ivanvojinovic/pipeline-git-branch-resource
    tag: v3.3

resources:

- name:         pipeline-git-branch-resource
  type:         pipeline-git-branch-resource-type
  source:
    project_name:         (( grab meta.project.name ))
    project_pipeline:     (( grab meta.project.pipeline ))
    project_git_uri:      (( grab meta.project.git_uri ))
    project_git_key:      (( grab meta.project.git_key ))
    project_docker_repo:  (( grab meta.project.docker_repo ))
    concourse_url:        (( grab meta.concourse.url ))
    concourse_username:   (( grab meta.concourse.username ))
    concourse_password:   (( grab meta.concourse.password ))

jobs:
- name: done-job
  plan:
  - get: pipeline-git-branch-resource
    trigger: true
  - task: done-task
    config:
      platform: linux
      image_resource:
        type: docker-image
        source:
          repository: docker.zipcar.io:443/cheetah_ruby
          tag: ruby23
      inputs:
      - name: pipeline-git-branch-resource
      run:
        path: sh
        args:
        - -exc
        - |
          env
